In [1]:
import pandas as pd

In [2]:
games = pd.read_csv('data/games.csv', index_col=0)
games.head()

,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
AppID,,,,,,,,,,,,,,,,,,,,,
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [3]:
indie_games = games[games['Genres'].str.contains('Indie')]

In [4]:
indie_games.sort_values('Peak CCU', ascending=False)

,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
AppID,,,,,,,,,,,,,,,,,,,,,
3419430,Bongo Cat,"Mar 5, 2025",0 - 20000,164168,0,0.00,0,0,Bongo cat needs your help. Bongo cat needz mor...,"['English', 'German', 'Dutch', 'Japanese', 'Ko...",...,7434,2225,4891,"Marcel Zurawka,Julius Krüger",Irox Games,"Single-player,Multi-player,Co-op,Online Co-op,...","Casual,Indie,Massively Multiplayer,Simulation,...",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
252490,Rust,"Feb 8, 2018",20000000 - 50000000,143870,0,19.99,50,5,The only aim in Rust is to survive. Everything...,"['English', 'French', 'Italian', 'German', 'Sp...",...,1246,3044,373,Facepunch Studios,Facepunch Studios,"Multi-player,MMO,PvP,Online PvP,Co-op,Online C...","Action,Adventure,Indie,Massively Multiplayer,RPG","Survival,Crafting,Multiplayer,Open World,Open ...",https://shared.akamai.steamstatic.com/store_it...,NaN
431960,Wallpaper Engine,"Nov 16, 2018",20000000 - 50000000,91184,0,3.99,20,1,Wallpaper Engine enables you to use live wallp...,"['English', 'German', 'Simplified Chinese', 'P...",...,135,1045,9,Wallpaper Engine Team,Wallpaper Engine Team,"Steam Achievements,Steam Trading Cards,Steam W...","Casual,Indie,Animation & Modeling,Design & Ill...","Mature,Utilities,Anime,Software,Design & Illus...",https://shared.akamai.steamstatic.com/store_it...,NaN
1671210,DELTARUNE,"Jun 4, 2025",1000000 - 2000000,83936,0,19.99,20,1,The next adventure in the UNDERTALE series has...,"['English', 'Japanese']",...,109,1160,151,tobyfox,tobyfox,"Single-player,Full controller support,Steam Cl...","Indie,RPG","Story Rich,Great Soundtrack,Pixel Graphics,Fun...",https://shared.akamai.steamstatic.com/store_it...,NaN
413150,Stardew Valley,"Feb 26, 2016",20000000 - 50000000,50662,0,8.99,40,1,Stardew Valley is an open-ended country-life R...,"['English', 'German', 'Spanish - Spain', 'Japa...",...,504,1728,127,ConcernedApe,ConcernedApe,"Single-player,Multi-player,Co-op,Online Co-op,...","Indie,RPG,Simulation","Farming Sim,Pixel Graphics,Multiplayer,Life Si...",https://shared.akamai.steamstatic.com/store_it...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2617350,MACHO SPINNER,"Dec 10, 2023",0 - 20000,0,0,2.69,0,0,"In the year XXXX AD, profound societal transfo...","['English', 'Simplified Chinese', 'Traditional...",...,0,0,0,NEOLAVI,indiegamesjapan,"Single-player,Multi-player,PvP,Online PvP,Stea...","Action,Indie","Action,Strategy,Tabletop,Idler,Tactical RPG,3D...",https://shared.akamai.steamstatic.com/store_it...,NaN
3162000,The Backrooms: Expedition,"Jul 1, 2025",0 - 20000,0,0,2.79,30,0,The Backrooms: Expedition is an immersive psyc...,['English'],...,0,0,0,Sylvester,Sylvester,"Single-player,Family Sharing","Action,Adventure,Indie","Horror,Walking Simulator,Psychological Horror,...",https://shared.akamai.steamstatic.com/store_it...,NaN
937970,Running Girl,"Nov 12, 2018",0 - 20000,0,0,9.99,0,0,Have you ever had a dream in which you had to ...,"['English', 'French', 'Italian', 'German', 'Sp...",...,0,0,0,TonAme,TonAme,"Single-player,Steam Achievements,Partial Contr...","Action,Adventure,Casual,Indie,Racing,Simulation","Casual,Action,Indie,Runner,Colorful,Stylized,R...",https://shared.akamai.steamstatic.com/store_it...,NaN
2704290,Liam FitzRoy kills everyone The game Part Zero,"Dec 14, 2023",20000 - 50000,0,0,0.00,0,0,Liam FitzRoy kills everyone The game Part Zero...,['English'],...,0,0,0,Rick Noiman,Rick Noiman,Single-player,"Action,Adventure,Indie,Free To Play","Adventure,Story Rich,FPS,First-Person,Shooter,...",https://shared.akamai.steamstatic.com/store_it...,NaN
1411030,Square Game,"Sep 25, 2020",0 - 20000,0,0,0.00,0,0,The long-lost classic puzzle from Windows XP P...,"['English', 'German']",...,0,0,0,OptiMAST,OptiMAST,"Single-player,Steam Achievements,Stats,Steam L...","Casual,Free To Play,Indie","Arcade,Casual,2D,Puzzle,Singleplayer,Psychedel...",https://shared.akamai.steamstatic.com/store_it...,NaN

In [5]:
indie_games.columns

Index(['Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age',
       'Price', 'Discount', 'DLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='str')

In [6]:
games['Categories'].str.split(',').explode().value_counts()

Categories
Single-player                   108003
Family Sharing                   95904
Steam Achievements               55736
Steam Cloud                      30354
Full controller support          25467
Multi-player                     20294
Partial Controller Support       13691
PvP                              12597
Steam Trading Cards              11377
Co-op                            11019
Steam Leaderboards                9235
Online PvP                        8920
Remote Play Together              7763
Shared/Split Screen               7433
Online Co-op                      6781
Custom Volume Controls            6515
Playable without Timed Input      6452
VR Only                           5787
Tracked Controller Support        5623
Shared/Split Screen PvP           5116
Stats                             5097
Shared/Split Screen Co-op         4307
Stereo Sound                      3960
Save Anytime                      3655
Mouse Only Option                 3194
Cross-Platform Multiplayer        3028
In-App Purchases                  2998
Camera Comfort                    2824
Steam Workshop                    2732
Remote Play on TV                 2589
Includes level editor             2580
Adjustable Difficulty             2530
Keyboard Only Option              2370
Captions available                1583
Color Alternatives                1524
MMO                               1339
VR Supported                      1195
Remote Play on Tablet             1105
LAN PvP                           1058
LAN Co-op                         1028
Surround Sound                    1020
Remote Play on Phone               953
Touch Only Option                  880
Adjustable Text Size               774
Subtitle Options                   746
HDR available                      395
Commentary available               294
VR Support                         233
Narrated Game Menus                226
Valve Anti-Cheat enabled           115
Steam Timeline                     104
Steam Turn Notifications            98
Includes Source SDK                 59
SteamVR Collectibles                38
Chat Text-to-speech                 35
Chat Speech-to-text                 29
Mods (require HL2)                   2
Mods                                 2
Name: count, dtype: int64

In [7]:
games['Genres'].str.split(',').explode().value_counts()

Genres
Indie                    80630
Casual                   50210
Action                   46220
Adventure                45141
Simulation               24114
Strategy                 22400
RPG                      20972
Free To Play             12172
Early Access             11091
Sports                    4882
Racing                    4079
Massively Multiplayer     2527
Utilities                 1077
Design & Illustration      580
Animation & Modeling       477
Education                  461
Violent                    414
Video Production           339
Game Development           320
Gore                       257
Audio Production           225
Software Training          219
Photo Editing              180
Web Publishing             112
Nudity                      94
Sexual Content              88
Accounting                  30
Movie                        2
Documentary                  1
Episodic                     1
Short                        1
Tutorial                     1
360 Video                    1
Name: count, dtype: int64

In [8]:
games['Release date'] = pd.to_datetime(games['Release date'], errors='coerce')
games['Release date'].sort_values(ascending=False)

AppID
4141790   2026-01-05
4182060   2026-01-04
3680350   2026-01-04
4152910   2026-01-04
3961990   2026-01-04
             ...
50        1999-11-01
20        1999-04-01
70        1998-11-19
232770    1997-11-14
282010    1997-06-30
Name: Release date, Length: 122611, dtype: datetime64[us]

In [12]:
(pd.Period(games['Release date'].max(), freq='Q') - 1).start_time

Timestamp('2025-10-01 00:00:00')

In [17]:
games['Linux'].value_counts()

Linux
False    106905
True      15706
Name: count, dtype: int64